services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mapaches_lectores
      MYSQL_USER: userdb
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
        - db_data:/var/lib/mysql
  appweb:
    build:
      context: .
      dockerfile: MapachesLectoresBackend/Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - db
#    volumes:
#      - .:/app
#      - nuget_cache:/root/.nuget/packages
volumes:
  db_data:
#  nuget_cache:
