services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mapaches_lectores
      MYSQL_USER: userdb
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
        - db_data:/var/lib/mysql
  appweb:
    build:
      context: ./MapachesLectoresBackend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - db
#    command: dotnet watch run  --project /app/MapachesLectoresBackend/MapachesLectoresBackend.csproj
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
volumes:
  db_data:
