services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mapaches_lectores
      MYSQL_USER: userdb
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
        - db_data:/var/lib/mysql
  appweb:
    build:
      context: ./MapachesLectoresBackend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - db
#    command: dotnet watch run  --project /app/MapachesLectoresBackend/MapachesLectoresBackend.csproj
    volumes:
      - .:/app
      - /app/bin
      - /app/obj

  mongodb:
    image: bitnami/mongodb:latest
    environment:
        - MONGODB_ROOT_USER=root
        - MONGODB_DISABLE_ENFORCE_AUTH=true
        - MONGODB_ROOT_PASSWORD=pass
    volumes:
        - mongo_data:/bitnami/mongodb
    ports:
        - "3309:27017"
volumes:
  db_data:
  mongo_data:
